### ISSUE TITLE
[Feature Request]: Key Documentation Enhancement

### ISSUE THREAD

**Issue by StefanThoma** [insightsengineering/teal.data#124]
### Feature description

I have somewhat of an outsiders perspective, so this may be obvious to people more familiar with this. 
I had the following experience trying to understand how to build teal apps: 

In `cdisc_data()` and more specifically in `cdisc_dataset()` it is not immediately clear to me:
- Why keys have to be specified
- Why (e.g., for "ADTR") multiple keys have to be specified
- What the keys are exactly used for
- Where I can find which keys I have to specify
- Why an error is returned if not all keys are specified 
  - If `cdisc_dataset()` realises that some key is missing, why does it not automatically fix it?

I believe the documentation with regards to keys could be improved. 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
Hi @StefanThoma, 

I believe the keys that you mentioned here are the `join_keys`. 

We started mentioning this topic in [teal](https://insightsengineering.github.io/teal/main/articles/including-adam-data-in-teal.html) and more detail explanation in in [teal.data](https://insightsengineering.github.io/teal.data/main/articles/join-keys.html). 

So that you can move forward, let me answer your questions:

> Why keys have to be specified

Keys are primary keys. 
When passing multiple datasets to the cdisc_data function, dataset relationship are set using keys to merge datasets together within teal apps.

> Why (e.g., for "ADTR") multiple keys have to be specified

Because in some cases (i.e. ADAE, ADLB), we may need several columns to uniquely identify rows in the dataset.

> What the keys are exactly used for

Keys are used to define relationship between datasets

> Where I can find which keys I have to specify

In order to find which keys you have to specify, you will need to understand the data first and identify the primary key(s). If you're dealing with cdisc dataset, you may use the default setup that we prepared in the package `?get_cdisc_keys`

> Why an error is returned if not all keys are specified

If I have to guess, the error probably around to duplicate PK values found when using the provided keys for the dataset or the related keys for joining not available in the other dataset. If you can provide with a screenshot, I can further diagnose this.

> If cdisc_dataset() realises that some key is missing, why does it not automatically fix it?

If user chooses to provide the keys for cdisc data, then I think it makes sense for user to provide the proper keys to define the relationship. This way, teal won't assume anything. Keep in mind that user don't have to have define the keys when running `cdisc_dataset()` and let teal assume the general relationship between datasets.

---

Back to the documentation, I was able to find the answers for your questions except the last one.
I do agree it's sporadic and we can do better to combine them into one place (probably teal.data).

We will assess this further and thanks again for the feedback.

**Comment by donyunardi** [comment]
Linking with insightsengineering/teal/issues/708

**Comment by donyunardi** [comment]
We've done teal.data refactor and updated most of our content.
Specifically, we talked about join keys in details here: 
https://insightsengineering.github.io/teal.data/main/articles/join-keys.html

The updated docs should give more context around the importance of join keys.

Closing this for now but feel free to reopen if needed.
