### ISSUE TITLE
Use hashes instead `identical` when checking reproducibility in `Dataset` objects

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/teal.data#27]
Provenance: 
```
Creator: kpagacz
```

**Comment by nikolas-burkoff** [comment]
Now that hashes have been moved out of teal.data I don't think we can do this?

**Comment by donyunardi** [comment]
> Now that hashes have been moved out of teal.data I don't think we can do this?

Is this the `$check` method? If so, then I still see them in this package:

https://github.com/insightsengineering/teal.data/blob/564b521d8dd321562e1bafb0016d9887346b7baa/R/MAETealDataset.R#L112

https://github.com/insightsengineering/teal.data/blob/564b521d8dd321562e1bafb0016d9887346b7baa/R/TealDataset.R#L501

One things that is missing from this issue is seeing the benchmark result to confirm that it's beneficial to change `identical` to `hashes`. 

However, considering that we're heading to the direction on removing teal.data, I think we should hold on pursuing this issue.

**Comment by gogonzo** [comment]
Not relevant anymore. Full implementation of teal_data already on main
