### ISSUE TITLE
Fix failed pipeline

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.data#325]
https://github.com/pawelru/ie_status?tab=readme-ov-file

**Comment by m7pr** [comment]
Starting new run https://github.com/insightsengineering/teal.data/actions/runs/10384115851 just in case
The last pipeline broke because we did not have `rmarkdown` installed for `noSuggests` and we could not create a vignette - I will investigate. https://github.com/insightsengineering/teal.data/actions/runs/10336789637/job/28612913785#step:7:98

**Comment by m7pr** [comment]
I think we could skip vignettes building, as there is no `rmarkdown` installed to render the vignettes https://stackoverflow.com/questions/41817313/r-cmd-check-skip-checking-re-building-of-vignette-outputs
however there is no `missing rmarkdown` error in vignettes build for `teal.slice` https://github.com/insightsengineering/teal.slice/actions/runs/10383145531/job/28747519682#step:7:95

**Comment by donyunardi** [comment]
> however there is no missing rmarkdown error in vignettes build for teal.slice

I think it's because rmarkdown is hard dependencies for htmlwidgets so it got installed during the pipeline.
https://github.com/ramnathv/htmlwidgets/blob/master/DESCRIPTION
https://github.com/insightsengineering/teal.slice/actions/runs/10383145531/job/28747519682#step:6:975
