### ISSUE TITLE
research on CodeDepends

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/teal.data#37]
https://cran.r-project.org/web/packages/CodeDepends/index.html

This package is able to build a tree of dependencies for a whole R script.

This package could be used to make users life easier. We could replace the #code> or #code ADSL ADTTE> chunks with automatic recognition of code needed to run specific table like get_code("ADSL","pathtoRscript").

Provenance: 
```
Creator: Polkas
```

**Comment by gogonzo** [comment]
I'm closing this issue as `CodeDepends` wouldn't fix our problems. Sometimes variable is dependent on a call which is impossible to link - for example when call sets variable in the custom environment, and then other call reuses this object implicitly. See for example `connection_open()` which can be equivalent of the opening ssh tunnel. I'd expect this 
```

library("CodeDepends")
sc <- readScript(
  txt = '
    library(pasta)
    conn <- pasta_open()
    ADSL <- pasta_data(path= "path/to/ADSL.pasta")
    ADTTE <- pasta_data(path= "path/to/ADTTE.pasta")
    ADRS <- pasta_data(path= "path/to/ADRS.pasta")
    
    ADSL$new_int <- 1L
    ADSL <- mutate(ADSL, new_char = "elo")
    ADRS$first_PARAMCD <- ADTTE$PARAMCD[1]
    ADTTE$first_AVISIT <- ADRS$AVISIT[1]
  '
)

getVariableDepends("ADTTE", frags = sc, checkLibraries = TRUE)
```

**Comment by m7pr** [comment]
Hey @gogonzo, the situation you listed above is a result of functions having side-effects (e.g. creation of a database hook that gets assigned to a global environment without explicit use of `<-`) and other functions assuming some side-effects has happened (e.g. some global variables exist and they use those global variables inside their body OR the environment of the execution changed - like with SSH tunel than moved the execution of the session to another machine).

Even though I think humanity should reject the usage of functions that create side-effects and stop using functions that assume global variables exist, sometimes such situation can not be omitted. I've seen this when working with databases when a database hook is assumed to exist in all functions working on this hook.

However I don't think code having side-effects is the total deal-breaker in here. We can provide extra formatting/commenting tags to make the code more understandable so that side-effects are connected with objects, and the code in clearer + the code-depencies are straightforward. Below is a couple of formatting options we could use, to over-come side-effects being undetected by CodeDepends. Of course we would need to write wrappers around CodeDepends that use our formatting/commenting tags.

# 1

```{R}

library("CodeDepends")
sc <- readScript(
  txt = '
    library(pasta)
    conn <- pasta_open() #@sideeffect all
    ADSL <- pasta_data(path= "path/to/ADSL.pasta")
    ADTTE <- pasta_data(path= "path/to/ADTTE.pasta")
    ADRS <- pasta_data(path= "path/to/ADRS.pasta")
    
    ADSL$new_int <- 1L
    ADSL <- mutate(ADSL, new_char = "elo")
    ADRS$first_PARAMCD <- ADTTE$PARAMCD[1]
    ADTTE$first_AVISIT <- ADRS$AVISIT[1]
  '
)

getVariableDepends("ADTTE", frags = sc, checkLibraries = TRUE)
```

# 2

```{R}

library("CodeDepends")
sc <- readScript(
  txt = '
    library(pasta)
    conn <- pasta_open() #@sideeffect ADSL ADTTE ADRS
    ADSL <- pasta_data(path= "path/to/ADSL.pasta")
    ADTTE <- pasta_data(path= "path/to/ADTTE.pasta")
    ADRS <- pasta_data(path= "path/to/ADRS.pasta")
    
    ADSL$new_int <- 1L
    ADSL <- mutate(ADSL, new_char = "elo")
    ADRS$first_PARAMCD <- ADTTE$PARAMCD[1]
    ADTTE$first_AVISIT <- ADRS$AVISIT[1]
  '
)

getVariableDepends("ADTTE", frags = sc, checkLibraries = TRUE)
```

# 3

```{R}

library("CodeDepends")
sc <- readScript(
  txt = '
    library(pasta)
    #@sideeffect_start all
    conn <- pasta_open() 
    #@sideeffect_end all
    ADSL <- pasta_data(path= "path/to/ADSL.pasta")
    ADTTE <- pasta_data(path= "path/to/ADTTE.pasta")
    ADRS <- pasta_data(path= "path/to/ADRS.pasta")
    
    ADSL$new_int <- 1L
    ADSL <- mutate(ADSL, new_char = "elo")
    ADRS$first_PARAMCD <- ADTTE$PARAMCD[1]
    ADTTE$first_AVISIT <- ADRS$AVISIT[1]
  '
)

getVariableDepends("ADTTE", frags = sc, checkLibraries = TRUE)
```

# 4

```{R}

library("CodeDepends")
sc <- readScript(
  txt = '
    library(pasta)
    #@sideeffect_start ADSL, ADTTE, ADRS
    conn <- pasta_open() 
    #@sideeffect_end ADSL, ADTTE, ADRS
    ADSL <- pasta_data(path= "path/to/ADSL.pasta")
    ADTTE <- pasta_data(path= "path/to/ADTTE.pasta")
    ADRS <- pasta_data(path= "path/to/ADRS.pasta")
    
    ADSL$new_int <- 1L
    ADSL <- mutate(ADSL, new_char = "elo")
    ADRS$first_PARAMCD <- ADTTE$PARAMCD[1]
    ADTTE$first_AVISIT <- ADRS$AVISIT[1]
  '
)

getVariableDepends("ADTTE", frags = sc, checkLibraries = TRUE)
```

Much more combinations can be proposed. Those `#@sideffect` tags bring connections between object in the code for sideeffects making the dependency tree restorable. This is not much effort on the user side, and for sure it gives a lot of benefits to the code, where you specify which side-effects have effects on which objects.

I would like to reopen the discussion, with your permission

**Comment by gmbecker** [comment]
I'm unsure of exactly what we're talking about here, but I will say that CodeDepends supports custom function handlers, so you can customize the handling of any particular functions. 

So you'd do something along the lines of
```
getVariableDepends("ADTTE", frags = sc, checkLibraries = TRUE, collector = inputCollector(pasta_open = handle_pasta_open, pasta_data = handle_pasta_data))
```
 Where `handle_pasta_data` and `handle_pasta_open` know how to model the relationship there. 

pasta doesn't appear to be a real package so I can't test this further, but the model here is that if the default general purpose input collector (which does the work under the hood) doesn't work for you, then you can create another with stronger assumptions that match your narrower scope.

**Comment by m7pr** [comment]
Thanks @gmbecker becker for the input. I think this might be too complicated to be handled for every separate dataset in comparison to what we have and what we discussed internally.

@gogonzo I have a working prototype of how I would like to get rid of cdisc_data specification (in teal::init) that reuses the data specification and the code. I am polishing up the code and planning to put my proposition here when I'm done.

The goal is to omit passing the code twice on a teal::init startup (once on an object creation, and second time on connecting the code to the data). Ultimately we can use comments/tags to navigate/connect sideeffects with the data that are not directly visible by just skimming the code

**Comment by m7pr** [comment]
@gogonzo the only drawback of my proposition is that `parse` (that I need to extract `srcref`) looses comments

```{R}
code = '
  ADSL <- goshawk::rADSL
  goshawk::rADLB-> ADLB
  iris2 <- iris # @effect ADLB ADSL
  ADLB <- list(ADLB, ADLB)
  '

parsed_code <- parse(text = code)
parsed_code
```

```{R}
expression(ADSL <- goshawk::rADSL, goshawk::rADLB-> ADLB, iris2 <- iris, 
    ADLB <- list(ADLB, ADLB))
```

```{R}
srcref <- attr(parsed_code, 'srcref')
srcref
```

```{R}
[[1]]
ADSL <- goshawk::rADSL

[[2]]
goshawk::rADLB-> ADLB

[[3]]
iris2 <- iris

[[4]]
ADLB <- list(ADLB, ADLB)
```
